### ISSUE TITLE
source & crusca

### ISSUE THREAD

**Issue by boltthrower142** [alexanderby/darkreader#103]
I'm new on github/darkreader/chrome, maybe I'll tell something obvious..

- is there some options to see the "view-source:" in darkmode?
- a simple page with bgcolor=white,
http://vocabolario.sns.it/Vocabolario/html/_s_Introduzione.html
it really remains white... why? :)

**Comment by RalphLesch** [comment]
> is there some options to see the "view-source:" in darkmode?

Not sure what you mean, but in general you can view the page source by right clicking into the page and choosing view source (second from bottom).

> a simple page with bgcolor=white,
> http://vocabolario.sns.it/Vocabolario/html/_s_Introduzione.html
> it really remains white... why? :)

This is because of the `[background]` selector, which applies to `<body background="images/home_02.gif" ...>`.
To test this, remove the background attribute from the body (right click, inspect, ...)
To fix this, you can edit the inversion fix file (fix_inversion.json), by using the Dark Reader developer tools (inversion fix editor). For e.g.:

- For all pages: Under `"common"` > `"invert"` replace `"[background]"` with `":not(body)[background]"`
and under `"noinvert"` replace `"[background] *"` with `":not(body)[background] *"`.
- Page specific fix: Add
```json
        {
            "url": "vocabolario.sns.it",
            "noinvert": "body[background]",
            "invert": "img[src]"
        },
```
You can leave out the `"invert": ...`, what ever looks and works better for you.

**Comment by alexanderby** [comment]
@RalphLesch is right, I've added his fix.
