### ISSUE TITLE
Noinvert rule works exclusively for "html"

### ISSUE THREAD

**Issue by mtman** [alexanderby/darkreader#108]
I'm trying to create a noinvert rule for Asana (looks like a React app) but no selector except `html` works, including `body`.

I've also tried:
```
body, body *,
.Sidebar, .Sidebar * {
    -webkit-filter: none !important;
    filter: none !important; 
}
```
For instance replacing a background works as expected, but nothing with a filter.

Any tips?

**Comment by alexanderby** [comment]
Seems like I have to make some diagram, this is a popular question.

When Dark Mode is on, `html { filter: invert(100%); }` rule is created and the whole page becomes inverted. We need to apply the filter the second time, so that when we add `"invert": "img, iframe"` to config we can get `img, iframe { filter: invert(100%); }` rule that will invert images again.

`"noinvert"` creates `{ filter: none; }` CSS rule and is needed when `"invert"` is applied to children of already inverted elements.

So, in your case you need something like
```json
{
    "invert": ".Sidebar",
    "noinvert": ".Sidebar *"
}
```
