### ISSUE TITLE
Syntax for background image in inline CSS

### ISSUE THREAD

**Issue by ruskiar** [alexanderby/darkreader#177]
I've been trying to stop DarkReader from inverting the background image on a login page. I've tried a bunch of different variations and I can't figure out whether it is a limitation of DarkReader but it's probably just me not doing it correctly.

Site: https://demo.aeries.net/aeries/Login.aspx?demo=True&user=admin&pwd=admin
Trying to make the background image show up in true color not inverted. The background image is in DynamicStyle as background-image. The inline CSS is what is tripping me up. I tried using the Chrome inspector to figure out the syntax but no luck.

Relevant bits of HTML:
`<head id="Head1">`
`...`
`     <style id="DynamicStyle">`
`           body{background-image: url('images/backgrounds/Cityscape-LosAngeles-HenningWitzel.jpg'); background-repeat: no-repeat; background-position: center center; background-attachment: fixed;}`
`     </style>`
`...`
`<style id="dark-reader-style" type="text/css">...</style>`
`</head>`

**Comment by RalphLesch** [comment]
With DarkReader, the html element gets inverted in general.
On your site, the background image is set for the body, so you need to either re-invert the body (which is not a good option, since it would make revert the entire inversion) or prevent it from getting inverted.

So my suggestion is to not invert `html` and invert all body children or only the ones needed (adjust `body > *` as needed), thus the body background image stays intact:
```json
        {
            "url": "demo.aeries.net",
            "invert": "body > *",
            "noinvert": "html"
        },
```

**Comment by ruskiar** [comment]
Thanks for the tip, I wasn't thinking in the way you mentioned (only inverting body via double invert) so I wasn't even going in the right direction
