### ISSUE TITLE
Dark video problem

### ISSUE THREAD

**Issue by happysurf** [alexanderby/darkreader#219]
Not all elements became dark in presence of videos.
Look this, http://www.nowvideo.li/video/e8c27b4fc9e8e the orizontal parts inside the video became white and not black.
In addition in other sites like this http://video.sky.it/news/diretta the black background became white, in my opinion the dark parts must be remain untouchable.

**Comment by RalphLesch** [comment]
First: bad (first) example, because of questionable legality of content!

About the actual problem:
The controls of the video in your first example are defined in the parent element of the video.
Since there is currently no parent selector in CSS (like `:has(video)` in jQuery, which is also [in a working draft for level 4 selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/:has)), a general fix for videos, including background and controls, would require more than a CSS-Style fix.

Although video controls are probably not always dark (on all sites) and thus should not be excluded from the inversion in general. So the first question would be, if a general non-inversion fix for video controls is actually better than a site-specific fix, like
```json
        {
            "url": "nowvideo.li",
            "invert": ".video-js",
            "noinvert": ".video-js *"
        },
```
Anyways, my approach in another project was to find the outermost parent (same size) via JS, that included both parent and controls for each video element and operate on that container.
Could be quite easily adapted for DarkReader if that actually brings a benefit for most videos.

### Black background
Your second example is site-specific and requires (currently) a custom fix, like
```json
        {
            "url": "video.sky.it",
            "invert": "#content",
            "noinvert": "#content *"
        },
```
I can write a pull request, if the site specific fixes solve the problems for the given examples. Please test them if you can, feedback would be nice.

**Comment by alexanderby** [comment]
Should work well with Dynamic Theme mode, though CSS is loading slow and there is a white flash.
