### ISSUE TITLE
 White flash when loading any page, new tab, or even opening Chrome

### ISSUE THREAD

**Issue by matt77hias** [alexanderby/darkreader#32]
To reproduce the problem:
1. Open Google Chrome, see a white flash.
2. Open any web page (no matter what color it is) and see the white flash again.
3. Open a new tab and (guess what?) the white flash again!

Is it possible to make this screen black as well?

**Comment by alexanderby** [comment]
I understand your irritation. Unfortunately all I can do is to report bugs to Chromium team. Here is the list of bugs I found https://productforums.google.com/forum/#!topic/chrome/M_gtcHph_ZQ

And here is the latest active discussion and progress https://bugs.chromium.org/p/chromium/issues/detail?id=470669

**Comment by matt77hias** [comment]
Thank you for the feedback.
I'll mark this one as close since Chrome/Chromium is responsible.

**Comment by hbt** [comment]
@alexanderby 
I love your extension but that white flash is the most annoying bug ever. 
I ended up losing my mind and forked chromium and wrote a quick fix https://github.com/hbtlabs/chromium-white-flash-fix

The chromium team is has been looking for an algorithmic fix since 2008. 
If you have a better solution, please get in touch with me.

Thank you again for darkreader.

**Comment by alexanderby** [comment]
That's a very heroic decision.
Would be great, if you will add ability to launch extensions and open Dev Tools in mobile Chrome version.
