### ISSUE TITLE
Override White Blank page between webpage loads.

### ISSUE THREAD

**Issue by thomasgroch** [alexanderby/darkreader#40]
I love Google Chrome and this extension, but these white flashes makes me crazy. Maybe someone could upgrade the code on this link and make it compatible to the newest chrome version.

http://stackoverflow.com/questions/16243105/google-chrome-override-white-blank-page-between-webpage-loads

Thanks

**Comment by subdiff** [comment]
In Chromium, there are certain bugs like holy grails, it seems. This issue is going on for years. I've just never used darkreader / dark themes until recently, so I didn't noticed it.

The Chromium team is working on a fix, but the problem is apparently a complicated one. In order to learn more about it and them hopefully soon landing a fix, you can read this fascinating bug report (people are even reporting health issues they have because of the flashes):
https://bugs.chromium.org/p/chromium/issues/detail?id=470669

**Comment by alexanderby** [comment]
They have fixed it by showing theme background color by default. So, install some dark theme, like Material Simple Dark Grey.
