### ISSUE TITLE
What is the license of this repository?

### ISSUE THREAD

**Issue by samtron1412** [alexanderby/darkreader#43]
I want to practice programming with Javascript and modify some code in this project (educational purpose), but I don't know what the license is. I think this repository needs a license.

**Comment by puranjayjain** [comment]
@samtron1412 although I am not the owner (or related to) the development of this project, since the project's source is open to pull requests and the author himself promotes bug fixes and tweaks you may modify a copy of this project as long as you don't violate the general fair usage policy.

Also you have mentioned educational purpose. Feel free to practice on this or any other project on github 😄

**Comment by alexanderby** [comment]
I don't know which license should I choose. Anyway this repository is a bad example to learn from. Here is a better example https://github.com/TargetProcess/tauCharts
