### ISSUE TITLE
Don't invert dark pages

### ISSUE THREAD

**Issue by MareinK** [alexanderby/darkreader#81]
I couldn't find an existing issue for this.

Currently the extension seems to blindly invert all pages, even ones that are already dark. Example: https://www.cs.ru.nl/~freek/fta/xindex.html

Perhaps it could check whether colours are already sufficiently dark before inverting them?

I know about `dark_sites.json`, but I'm talking about automatic detection of dark pages.

**Comment by RalphLesch** [comment]
I am working on a detection algorithm for dark pages, but it is not that easy, since it should be reliable and efficient for all/most pages.
I got two approaches so far:

1. Traverse DOM tree and determine background brightness of the biggest elements (which take the most screen space) and maybe foreground colors, too.
Not that easy with transparency and possibly absolute positioned elements deeper in the DOM tree.
2. Get pixel colors over screen. Probably randomly distributed over entire page for a compromise between accuracy and performance.
But getting the image representation / pixel data of the page, like with [`captureVisibleTab`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/captureVisibleTab), will probably already be too slow.

Currently, I am going for option 1, but the base is the same (color => brightness => dark/light), which I already got.
If anybody has better ideas, I am thankful for suggestions or discussing the approach.

**Comment by alexanderby** [comment]
@RalphLesch Have a look at Disqus script, it determines which theme to show, dark or light.

**Comment by RalphLesch** [comment]
Option 2 is actually not that bad. Loading and analyzing the entire image/screenshot (max. `screen width * hight`) seems to be much faster then I expected.
But I will take a look at Disqus, thx.

**Comment by RalphLesch** [comment]
### About Disqus
According to the [Disqus documentation](https://help.disqus.com/customer/en/portal/articles/545277-disqus-appearance-tweaks) it uses the inherited text color to determine the used theme, as it is used within an iframe, afaik.
Determining brightness of text and background color was my idea, too ([Optoin 1](#issuecomment-356292068)). The problem is reliability, i.e. finding the relevant elements in the entire document, not only of a single element (parent) like Disqus does:
A small black on white element (like a dark header) is less relevant compared to the big main white on black element for the overall brightness. Same goes for a dark `<body>` background if the main text block in the foreground has a white background and uses the most screen space.

### Method and integration for DarkReader
I think the "screenshot" analysis is the most accurate, but unpractical, because the page needs to be rendered and visible. Ideally the right style should be chosen before the page is shown or at least as soon as possible, before DarkReader's style is applied.
I will finish and test the DOM tree analysis, which is less reliable, but does not need a rendered page and should be pretty fast with a depth / child number limit.

@alexanderby: A tip for where to integrate the dark/light check for not configured pages best in the code would be very helpful, for testing the method, too. Probably in [FilterCssGenerator.createCssCode](https://github.com/alexanderby/darkreader/blob/19ce3f469357145e99bdfd6854f2069facf3c0bd/src/background/filter_css_generator.ts#L74)? Or will that change with the UI refactoring, too?

**Comment by RalphLesch** [comment]
First version of the DOM tree analysis is implemented. Detection rate looks good so far (further test needed). With limited depth and child number it should only take a few ms to check for a native dark style.

But, in contrast to DarkReader's style injection at `document_start` (or loading of `<head>`), the analysis has to run at `document_end` (`<body>` loaded). So removing the injected style for native dark sites would be the better option to keep native white sites (the majority) inverted from the start.
Downside is, that you will see native dark sites inverted (bright) for a short time, at least on first (domain) visit, assuming we cache/save the detected dark sites/domains.
Although I do not think you can prevent that completely for all sites anyways.

I will push it as stand alone module / library to GitHub soon.

DarkReader integration will need some work. Not sure about the cache for detected native dark domains: permanently in dark site list or only temporary for browser session if privacy / (local) tracking is a concern?

**Comment by alexanderby** [comment]
It is also possible to setup mutation observer, that will listen for `<style>` updates.

Overall browser script that detects if website is dark will be enough at the moment. I will create a roadmap or a board to prioritize and schedule all that needed fixes.

**Comment by RalphLesch** [comment]
Yea, I thought about analyzing style sheets (`<style>` and `<link rel="stylesheet">`) while `<head>` is loading (before `<body>` is shown), too, like with via `document.styleSheets`.
Could be an option for a first clue whether the site has a dark or light style.
But, I see several problems:
1. Cross domain style sheets (via `<link>`): to my knowledge, they cannot be inspected directly for security purposes. Only way I see would be an additional cross-domain request to get the script source.
2. Dark and light elements in styles: will give inconclusive results, since you can only use selectors to weight them (foreground > background), which works only for selectors like `html` or `body` etc.
3. Inline styles: cannot be analysed before `<body>` gets loaded (and shown) anyways.

A combination of both style sheet and DOM analysis could minimize the wrong inversions, though.
Will keep that in mind as an possible improvement, thanks!

If we take this further, a dynamic inversion of site elements could even be possible, since the DOM tree gets analysed anyways. But one step at a time :)
DarkReader integration comes first and will be my priority for now. I will try to include it as an optional feature, mostly separate from the rest of the code, to minimize conflicts.

**Comment by h3298** [comment]
> @RalphLesch 
> **If anybody has better ideas, I am thankful for suggestions or discussing the approach.**

I'm no expert but want to share some ideas: maybe detection should proceed in stages, so different algorithms are applied depending on page content and complexity.  First, to handle uncomplicated sites like the one reported in the first post:

**If --**
  page has no scripts, styles, etc (and)
  you find a match on the following expression: < body * bgcolor="#000000" * >
**--do not invert.**

That would cover the vast majority of uncomplicated pages like this which have a dark background since #000000 is the most common choice of dark background color.
____

For pages with a background image that are currently being inverted incorrectly, try right-clicking in Firefox and "**view background image**".  In cases where Mozillas background detection method would work, you can then use other methods like this to determine background color & brightness:

https://stackoverflow.com/questions/2541481/get-average-color-of-image-via-javascript
https://stackoverflow.com/questions/13762864/image-dark-light-detection-client-sided-script

If the average brightness is closer to dark than light, do not invert.

**Comment by alexanderby** [comment]
Dynamic Theme analyzes colors and background images of CSS <link> and `<style>` elements parsed by browser (and inline style="" attributes if specified in config). I think there is no other way to do it better, only performance improvements of analysis process.

**Comment by vanniktech** [comment]
Darkreader is inverting my dark themed YouTube currently. Is this intended or not? 

Skimming through the issues it seems like there is some mechanism in place to detect whether dark theme has been enabled or not.

**Comment by vanniktech** [comment]
I would have expected that the default native black theme from Youtube would supersede the plugin.

**Comment by alexanderby** [comment]
If Dynamic mode is enabled, it will leave dark backgrounds dark and light texts light. But the Filter mode is rather primitive. Each mode has its advantages and disadvantages. Still Dynamic mode has some known issues on YouTube.

**Comment by NN---** [comment]
http://youtrack.jetbrains.com/ has dark mode and Dark Reader doesn't recognize it well.

**Comment by irvnriir** [comment]
I do not think this should be closed .
